apiVersion: v1
data:
  replicas: "3"
  diskGiB: "120"
  memoryMiB: "32768"
  networkName: "DSwitch-VM Network"
  numCPUs: "12"
  numCoresPerSocket: "2"
  datacenter: "Home"
  datastore: "vsanDatastore"
  folder: "/Home/vm/hub-h4242"
  resourcepool: "/Home/host/SCCD/Resources"
  server: "192.168.0.10"
kind: ConfigMap
metadata:
  name: machineset-infra-vsphere
  namespace: policies
