apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base

components:
  - ../../components/application-controller-cluster-admin
  - ../../components/policy-generator
